var _surf = surface_create(room_width, room_height)
var _alpha = amp / 0.02
surface_set_target(_surf)
draw_clear_alpha(c_white, 0)
draw_circle_color(x, y, image_xscale * 64, c_white, c_white, false)
shader_reset()
gpu_set_blendmode(bm_min)
shader_set(shd_wave)
shader_set_uniform_f(timeUniform, waveTime)
waveTime++
shader_set_uniform_f(frequencyUniform, freq)
shader_set_uniform_f(amplitudeUniform, amp)
draw_surface(application_surface, camera_get_view_x(view_camera[0]), camera_get_view_y(view_camera[0]))
shader_reset()
gpu_set_blendmode(bm_normal)
surface_reset_target()
draw_surface(_surf, 0, 0)
surface_free(_surf)
draw_set_alpha(_alpha)
draw_set_alpha(1)